# Configure dependabot automatic version upgrades
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: maven
    directory: "/map-layers/"
    schedule:
      interval: weekly
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
    cooldown:
      semver-major-days: 10
      default-days: 5
    groups:
      # Group minor updates together
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/web-ui/"
    schedule:
      interval: weekly
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
    cooldown:
      semver-major-days: 10
      default-days: 5
    groups:
      # Group minor updates together
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
      time: "04:30"
      timezone: America/New_York
    labels:
      - dependencies
