name: Web UI Checks

on:
  pull_request:
    paths: 'web-ui/**'
  push:
    branches:
      - main

jobs:
  test-web-ui:
    name: Test and validate code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Lint with Oxlint
        run: npm run lint
      - name: Check Types
        run: npm run types
      - name: Check Formatting
        run: npm run format-check
  build-web-ui:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - run: npm run build
